# Exclude a variety of commonly ignored directories
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "migrations",
    "docs",
]

# Same as Black
line-length = 88

[lint]
fixable = ["ALL"]
select = ["E", "F"]
